import useUseRoute from "@/hooks/useUseRoute";
import { Inter } from "next/font/google";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { handlePush } = useUseRoute();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Welcome to Landing page</h1>
        <button onClick={() => handlePush("/signin")}>SignIn</button>
        <button onClick={() => handlePush("/signup")}>SignUp</button>
      </main>
    </>
  );
}
